emarket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from emarket import settings
from .views import home_page, header, footer, about_page

from django.views.static import serve
# from django.conf.urls import url


urlpatterns = [
    path('', home_page),
    path('', include('emarket_account.urls')),
    path('', include('emarket_products.urls')),
    path('', include('emarket_contact.urls')),
    path('', include('emarket_order.urls')),
    path('about-us', about_page),
    path('header', header, name="header"),
    path('footer', footer, name="footer"),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]


if settings.DEBUG:
    #add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emarket_products/urls.py
from django.urls import path

from .views import ProductsList, product_detail, SearchProductsView, ProductsListByCategory, products_categories_partial

urlpatterns = [
    path('products', ProductsList.as_view()),
    path('products/search', SearchProductsView.as_view()),
    path('products/<category_name>', ProductsListByCategory.as_view()),
    path('products/<productId>/<name>', product_detail),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial')
]

emarket_products/models.py
from django.db.models import Q
from django.db import models
import os
from emarket_products_category.models import ProductCategory


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/{final_name}"


def upload_gallery_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    final_name = f"{instance.id}-{instance.title}{ext}"
    return f"products/galleries/{final_name}"


# Create your models here.


class ProductsManager(models.Manager):
    def get_active_products(self):
        return self.get_queryset().filter(active=True)

    def get_products_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)

    def get_by_id(self, product_id):
        qs = self.get_queryset().filter(id=product_id)
        if qs.count() == 1:
            return qs.first()
        else:
            return None

    def search(self, query):
        lookup = (
                Q(title__icontains=query) |
                Q(description__icontains=query) |
                Q(tag__title__icontains=query)
        )
        return self.get_queryset().filter(lookup, active=True).distinct()


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    price = models.IntegerField(verbose_name='قیمت')
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True, verbose_name='تصویر')
    active = models.BooleanField(default=False, verbose_name='فعال/غیرفعال')
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name='دسته بندی ها')
    visit_count = models.IntegerField(default=0, verbose_name='تعداد بازدید')

    objects = ProductsManager()

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f"/products/{self.id}/{self.title.replace(' ', '-')}"


class ProductGallery(models.Model):
    title = models.CharField(max_length=150, verbose_name='عنوان')
    image = models.ImageField(upload_to=upload_gallery_image_path, verbose_name='تصویر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural = 'تصاویر'

    def __str__(self):
        return self.title

emarket_products/views.py
import itertools

from django.shortcuts import render
from django.views.generic import ListView

from emarket_order.forms import UserNewOrderForm
from .models import Product, ProductGallery
from django.http import Http404
from emarket_products_category.models import ProductCategory
from emarket_tag.models import Tag


# Create your views here.

# def products(request):
#     context = {}
#     return render(request, 'products/products_list.html', context)


class ProductsList(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.get_active_products()


class ProductsListByCategory(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        category_name = self.kwargs['category_name']
        category = ProductCategory.objects.filter(name__iexact=category_name).first()
        if category is None:
            raise Http404('صفحه ی مورد نظر یافت نشد')
        return Product.objects.get_products_by_category(category_name)


def my_grouper(n, iterable):
    args = [iter(iterable)] * n
    return ([e for e in t if e is not None] for t in itertools.zip_longest(*args))


def product_detail(request, *args, **kwargs):
    selected_product_id = kwargs['productId']
    new_order_form = UserNewOrderForm(request.POST or None, initial={'product_id': selected_product_id})

    product: Product = Product.objects.get_by_id(selected_product_id)
    if product is None or not product.active:
        raise Http404('محصول مورد نظر یافت نشد')

    product.visit_count += 1

    product.save()

    related_products = Product.objects.get_queryset().filter(categories__product=product).distinct()

    grouped_related_products = my_grouper(3, related_products)

    galleries = ProductGallery.objects.filter(product_id=selected_product_id)

    grouped_galleries = list(my_grouper(3, galleries))

    context = {
        'product': product,
        'galleries': grouped_galleries,
        'related_products': grouped_related_products,
        'new_order_form': new_order_form
    }
    return render(request, 'products/product_detail.html', context)


class SearchProductsView(ListView):
    template_name = 'products/products_list.html'
    paginate_by = 6

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            return Product.objects.search(query)
        return Product.objects.get_active_products()


def products_categories_partial(request):
    categories = ProductCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'products/products_categories_partial.html', context)

emarket_products/templates/products/product_detail.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product.image.url }}" alt="">
                                <h3>بزرگنمایـی</h3>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    {% for gallery_list in galleries %}
                                        <div class="item {{ forloop.first|yesno:'active,' }}">
                                            {% for product_gallery in gallery_list %}
                                                <a href=""><img src="{{ product_gallery.image.url }}"
                                                                alt="{{ product_gallery.title }}"
                                                                style="width: 90px;height: 90px"></a>

                                            {% endfor %}

                                        </div>
                                    {% endfor %}
                                </div>

                                <!-- Controls -->
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </div>

                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->
                                <img src="{% static 'images/product-details/new.png' %}" class="newarrival" alt="">
                                <div>
                                    <h2>{{ product.title }}</h2>
                                    <p>شناسـه : {{ product.id }}</p>
                                </div>
                                <div>
									<span>
										<span>قیمت : {{ product.price }} تومان</span>
									</span>
                                    <span>
                                        <form method="post" action="/add-user-order">
                                            {% csrf_token %}
                                            {{ new_order_form.product_id }}
										<label>تعداد :</label>
										    {{ new_order_form.count }}
										<button type="submit" class="btn btn-fefault cart">
											<i class="fa fa-shopping-cart"></i>
											افـزودن به سبـد خریـد
										</button>
                                        </form>
									</span>
                                </div>
                                <div>
                                    <p><b>موجـودی :</b> در انبـار موجود می باشد</p>
                                    <p><b>شرایـط :</b> جدیـد</p>
                                    <p><b>برنـد :</b> برنـد </p>
                                </div>
                               

                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#details" data-toggle="tab">جزئیات</a></li>
                                
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade" id="details">
                                <div class="col-md-12">
                                    <p>
                                        {{ product.description }}
                                    </p>
                                </div>
                            </div>


                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">
                                   
                                    <p> {{ product.description }}</p>
                                    
                                    
                                </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->

                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">محصولات پیشنهادی</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for product_list in related_products %}
                                    <div class="item {% if forloop.first %} active {% endif %}">
                                        {% for product in product_list %}
                                            {% include 'products/product_item_component.html' with product=product %}
                                        {% endfor %}
                                    </div>
                                {% endfor %}


                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel"
                               data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel"
                               data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--/recommended_items-->

                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">

                        {% render_partial 'products_categories_partial' %}

                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

emarket_products/templates/products/product_item_component.html
<div class="col-sm-4 pull-right">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <img src="{{ product.image.url }}" alt="">
                <h2>{{ product.price }} تومان</h2>
                <p>{{ product.title }}</p>
                <a href="{{ product.get_absolute_url }}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>مشاهده محصول</a>
            </div>
            <div class="product-overlay">
                <div class="overlay-content">
                    <h2>{{ product.price }} تومان</h2>
                    <p>{{ product.title }}</p>
                    <a href="{{ product.get_absolute_url }}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i> مشاهده محصول 
                        </a>
                </div>
            </div>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{{ product.get_absolute_url }}"><i class="fa fa-plus-square"></i>مشاهده</a></li>
                
            </ul>
        </div>
    </div>
</div>

emarket_products/templates/products/products_categories_partial.html
<h2>دسته بندی محصولات</h2>
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title"><a href="/products">همه</a></h4>
        </div>
    </div>
    {% for category in categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a href="/products/{{ category.name }}">{{ category.title }}</a></h4>
            </div>
        </div>
    {% endfor %}

</div><!--/category-productsr-->

emarket_products/templates/products/products_list.html
{% extends 'shared/_MainLayout.html' %}
{% load static %}
{% load render_partial %}

{% block content %}

    <section>
		<div class="container">
			<div class="row">

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">لیست محصولات</h2>
						{% for product in page_obj %}
                            {% include 'products/product_item_component.html' with product=product %}
                        {% endfor %}

                        <div class="clearfix"></div>
						<ul class="pagination">
                            {% if page_obj.has_previous %}
                               <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                        {% for page in paginator.page_range %}
                            {% if page == page_obj.number %}
                                <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                        {% endif %}
						</ul>
					</div><!--features_items-->
				</div>

				<div class="col-sm-3">
					<div class="left-sidebar">

                     {% render_partial 'products_categories_partial' %}

					</div>
				</div>

			</div>
		</div>
	</section>

{% endblock %}